export const ActionTypes = {
  SET_CHARACTERS: "SET_CHARACTERS",
  ADD_CHARACTER: "ADD_CHARACTER",
  SET_FAVORITES_CHARACTERS: "SET_FAVORITES_CHARACTERS",
  REMOVE_FAVORITES_CHARACTERS: "REMOVE_FAVORITES_CHARACTERS",
};
